---
- name: Apache server installed for Bancolombia
  hosts: all

  tasks:
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest
 
  - name: ensure postgresql is at the latest version
    yum:
      name: postgresql
      state: latest
 
  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: latest

  - name: firewalld enabled and running
    service:
      name: firewalld
      enabled: true
      state: started

  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
      
  - name: firewalld permits port postgresql
    firewalld:
      port: 5432/tcp
      permanent: true
      state: enabled

  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started
      
  - name: ensure that postgresql is started
    service:
      name: postgresql
      enabled: true
      state: started
